create table answers (answer_id bigint not null auto_increment, answer_value varchar(255), question_id bigint not null, primary key (answer_id)) engine=InnoDB;
create table comments (comment_id bigint not null auto_increment, comment_value varchar(255), survey_id bigint not null, primary key (comment_id)) engine=InnoDB;
create table questions (question_id bigint not null auto_increment, question_text varchar(255), survey_id bigint not null, primary key (question_id)) engine=InnoDB;
create table surveys (survey_id bigint not null auto_increment, survey_description varchar(255), survey_title varchar(255), primary key (survey_id)) engine=InnoDB;
create table users (user_id bigint not null auto_increment, user_date varchar(255), user_email varchar(255), user_name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_surveys (user_id bigint not null, survey_id bigint not null) engine=InnoDB;
alter table answers add constraint FK3erw1a3t0r78st8ty27x6v3g1 foreign key (question_id) references questions (question_id);
alter table comments add constraint FKufkhjafheycxsyfih634v5f0 foreign key (survey_id) references surveys (survey_id);
alter table questions add constraint FKnf38uiy78c0g0tmo68btk3y0p foreign key (survey_id) references surveys (survey_id);
alter table users_surveys add constraint FKd9mp10dhxtyhetf3j6u5s6m3y foreign key (survey_id) references surveys (survey_id);
alter table users_surveys add constraint FKeopmks0b11k8cde0vnpkejrgq foreign key (user_id) references users (user_id);
